### ISSUE TITLE
Use Parcel instead of Webpack

### ISSUE THREAD

**Issue by gamedevsam** [yandeu/phaser3-multiplayer-with-physics#10]
Webpack configs are yet another thing we have to maintain. I think Parcel is faster, has reasonable defaults, and would make implementing hot reloading easier.

**Comment by yandeu** [comment]
I do not agree. Webpack is the tool to use and is much more powerful.

**Comment by gamedevsam** [comment]
Fair enough, it's also a solved problem, closing the issue.
