### ISSUE TITLE
Error when player timeout

### ISSUE THREAD

**Issue by hungpqz** [yandeu/phaser3-multiplayer-with-physics#14]
I got this error: Error: ENOENT: no such file or directory, open 'C:\Game Dev\phaser3-multiplayer-with-physics\node_modules\@geckos.io\phaser-on-nodejs\lib\node:internal\process\task_queues'

it happened when player reach timeout after export const USER_KICK_TIMEOUT = 60_000 // 1 minute

Please help me fix this

**Comment by hungpqz** [comment]
Whenever player ends session, the app will crash. For example: I close stats page, It also crash

**Comment by yandeu** [comment]
Unfortunately, the code of this example is out of date.
It only serves as a reference.

**Comment by hungpqz** [comment]
I think this is great work, and we can make it better :) wish I can contribute some fixes for this project like change in 'source-map-support'...

**Comment by jupiter211developer** [comment]
Hi, Mr Yandeu!
Could you tell me the reason why this server quits when client closes window?
I want to know the reason. Please help me!
My skype id is live:.cid.930aaf0b06b3baf6.

**Comment by jupiter211developer** [comment]
I saw your heroku sample works well. Is it probably a little different source? I really appreciate if you give me an answer.

**Comment by yandeu** [comment]
Unfortunately I don't know. It is an old example. I don't not plan to keep it updated.
