### ISSUE TITLE
I want to call API from server side, but Phaser on Nodejs not allow

### ISSUE THREAD

**Issue by hungpqz** [yandeu/phaser3-multiplayer-with-physics#15]
I want to call API to save score from my game using phaser on nodejs:

`let res = await axios.post(API_GAME_SCORE, payload,config);`

and I got this error:

`Error: ENOENT: no such file or directory, open ‘C:\Game Dev\RockRun\node_modules@geckos.io\phaser-on-nodejs\lib\https:\api-testing.therocks.io\api\v1.0\game\score\update’`

I think because of fakeXMLHttpRequest 

Do you have any solution for this?

Thanks

**Comment by yandeu** [comment]
Try https://www.npmjs.com/package/node-fetch
