### ISSUE TITLE
Weird | `npm install` failed, but `npm start` works for local server running

### ISSUE THREAD

**Issue by ghost** [yandeu/phaser3-multiplayer-with-physics#16]
Hi,
Just after having cloned the repo, I tried to install node modules by `npm install`.
But it fails with some errors which seem to be related with typescript syntax.
However, I can execute `npm start` - i.e. `npm run dev` so that the local game server runs properly on port 3000.

![image](https://user-images.githubusercontent.com/116804904/204411733-d91077b9-9d39-4812-85b5-9416ac667835.png)

![image](https://user-images.githubusercontent.com/116804904/204411851-4cc3588e-3f79-4162-b04f-21c3a8bcac81.png)

I cannot understand why. Please help me!

**Comment by yandeu** [comment]
It's an old example. I don't really know what the error is. 

Today I would use [`https://github.com/yandeu/arcade-physics`](https://github.com/yandeu/arcade-physics) instead of [`https://github.com/geckosio/phaser-on-nodejs`](https://github.com/geckosio/phaser-on-nodejs). It's much much faster.

**Comment by ghost** [comment]
@yandeu Thanks for your kind reply.
`arcade-physics` looks much better!

![image](https://user-images.githubusercontent.com/116804904/204537340-70bca1e6-71e9-4340-b658-28e413d81579.png)
