### ISSUE TITLE
Compiled files are missing?

### ISSUE THREAD

**Issue by thecatontheflat** [yandeu/phaser3-multiplayer-with-physics#2]
Thanks for sharing this code!

I couldn't run it without TypeScript. 
I guess the repo should also include compiled files?

**Comment by yandeu** [comment]
You're welcome :)

I included TypeScript in the package.json. Isn't that enough? What compiled files do you mean?

**Comment by thecatontheflat** [comment]
I guess I just wanted to read compiled JS files instead of TS, as I didn't work with TS before. But after spending a few hours I realised it is actually much better ;) Thanks!
